name: aqueduct
version: 4.0.0-b1
description: A modern HTTP server application framework, ORM and OAuth2 provider with OpenAPI 3.0 integration. Foundation for REST, RPC or GraphQL services.
homepage: https://aqueduct.io
documentation:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  analyzer: ^1.3.0
  conduit_config: ^1.0.0-b1
  conduit_isolate_exec: ^1.0.0-b1
  conduit_open_api: ^1.0.0-b3
  conduit_password_hash: ^1.0.0-b1
  conduit_runtime: ^1.0.0-b1
  crypto: ^3.0.0
  logging: ^1.0.0
  meta: ^1.1.5
  path: ^1.6.1
  postgres: ^2.1.1
  pub_cache: ^0.3.0
  pub_semver: ^2.0.0
  yaml: ^3.1.0

dev_dependencies:
  matcher: '>=0.12.3 <0.14.0'
  test: ^1.3.0
  http: ^0.13.0
  fs_test_agent: ^1.0.0-b1
  aqueduct_test:
    path: ../aqueduct_test

dependency_overrides:
  # conduit_common: 
  #   path: ../../common
  # conduit_open_api:
  #   path: ../../open-api-dart    

executables:
  aqueduct: aqueduct
