name: wildfire
description: An conduit application with a database connection and data model.
version: 0.0.1
homepage: https://github.com/conduit-dart/conduit-codable
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  conduit: ^5.1.0
  conduit_core: ^5.1.0
  conduit_postgresql: ^5.1.0

dev_dependencies:
  test: ^1.25.2
  conduit_test: ^5.1.0
