name: conduit_postgresql
description: The postgresql ORM for conduit.
version: 5.0.0
repository: https://github.com/conduit-dart/conduit

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  collection: ^1.17.1
  conduit_core: ^5.0.0
  postgres: ^3.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.6
