name: conduit_common
description: Common classes shared by conduit projects.
version: 5.1.3
home: https://www.theconduit.dev
repository: https://github.com/conduit-dart/conduit
issue_tracker: https://github.com/conduit-dart/conduit/issues

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  conduit_open_api: ^5.1.3

dev_dependencies:
  lints: ^4.0.0
