name: conduit_common
version: 5.0.1
description: Common classes shared by conduit projects.
repository: https://github.com/bsutton/conduit-orm
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  conduit_open_api: ^5.0.1
dev_dependencies:
  lints: ^3.0.0
