name: dependency
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  conduit_runtime:
    path: ../../runtime

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.2
