name: dependency
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  conduit_runtime:
    path: ../../runtime

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.6
