name: conduit_runtime
version: 5.1.4
description: Provides behaviors and base types for packages that can use mirrors and be AOT compiled.
home: https://www.theconduit.dev
repository: https://github.com/conduit-dart/conduit
issue_tracker: https://github.com/conduit-dart/conduit/issues

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  analyzer: ^6.5.0
  args: ^2.0.0
  conduit_isolate_exec: ^5.1.4
  io: ^1.0.4
  package_config: ^2.1.0
  path: ^1.9.0
  pubspec_parse: ^1.2.3
  yaml: ^3.1.2

dev_dependencies:
  fs_test_agent:
    path: ../fs_test_agent
  lints: ^4.0.0
  test: ^1.25.2
