name: conduit_core
version: 5.1.1
description: This is the core of the framework.
home: https://www.theconduit.dev
repository: https://github.com/conduit-dart/conduit
issue_tracker: https://github.com/conduit-dart/conduit/issues

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  analyzer: ^6.5.0
  args: ^2.4.2
  collection: ^1.18.0
  conduit_common: ^5.1.1
  conduit_config: ^5.1.1
  conduit_isolate_exec: ^5.1.1
  conduit_open_api: ^5.1.1
  conduit_password_hash: ^5.1.1
  conduit_runtime: ^5.1.1
  crypto: ^3.0.3
  io: ^1.0.4
  logging: ^1.2.0
  meta: ^1.12.0
  path: ^1.9.0
  postgres: ^3.1.1
  pub_semver: ^2.1.4
  recase: ^4.1.0
  yaml: ^3.1.2

dev_dependencies:
  conduit_postgresql:
    path: ../postgresql
  conduit_test:
    path: ../test_harness
  fs_test_agent:
    path: ../fs_test_agent
  http: ^1.2.1
  lints: ^4.0.0
  matcher: ^0.12.16+1
  mockito: ^5.4.4
  test: ^1.25.2
  web_socket_channel: ^3.0.0
