name: conduit_password_hash
version: 5.1.3
description: PBKDF2 password hashing utility
home: https://www.theconduit.dev
repository: https://github.com/conduit-dart/conduit
issue_tracker: https://github.com/conduit-dart/conduit/issues

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  crypto: ^3.0.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.2
