name: conduit_config
version: 5.0.1
description: A safe and convenient way to read YAML configuration files.
repository: https://github.com/conduit-dart/conduit-config.git
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  conduit_runtime: ^5.0.1
  meta: ^1.3.0
  yaml: ^3.1.0
dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.6
